### PR TITLE
EphemeralKafkaCluster can have brokers with customized properties

### PR DESCRIPTION
**Pull request by mtillu**
EphemeralKafkaCluster does not have the ability to spin up brokers with overridden properties. Submitting this PR to support this use case. 

Please let me know if you have any questions/concerns/comments.

### CODE REVIEW

**Comment by mtillu** [comment]
@charithe - Please have a look. Thanks!

**Comment by mtillu** [comment]
@charithe Thanks for accepting the PR. Is there a possibility to update the release version?

**Comment by charithe** [comment]
I just released 4.1.8 and it contains this patch.

**Comment by mtillu** [comment]
Amazing. Thank you very much!

**Pull request merged**
