### PR TITLE
Allow user to override consumer config.

### PR DESCRIPTION
**Pull request by aeolus**
We have some use cases which requires to override consumer config. The patch allow user to override consumer config.

### CODE REVIEW

**Comment by charithe** [comment]
Why not just create your own consumer?

```java
Properties defaultConsumerProps = rule.consumerConfig();
defaultConsumerProps.putAll(yourOverrideProps);
KafkaConsumer<String,String> consumer = new KafkaConsumer<>(defaultConsumerProps, new StringDeserializer(), new StringDeserializer());
...
```

**Comment by aeolus** [comment]
Hi,

Thank you for the reply. We still like and want to use the pollMessage/2 which currently doesn't allow user to inject own consumer. Do you mean you prefer to extend pollMessage instead?

Our requirement is we just want to override one or two default consumer properties due to our use case. Sure, we could create our own consumer but then reading/poll message would be duplicated code as the Rule currently has right now.

**Comment by charithe** [comment]
What are the consumer properties you want to add? If they are something fundamental that I have missed, I'd be happy to add them. 

The reason I am reluctant to make the consumer properties configurable is because the consumer methods are just provided for convenience. I don't see the benefit of customising the default consumer of the rule because those changes will only live through in the unit test and won't be part of your actual source code. Maybe I am missing something obvious. Can you explain what your use case is?

**Comment by makkan** [comment]
We have an integration test where our application is posting to several different topics, then using the kafka rule consumer to read them. Kafka has a metadata max age which is set to 30 seconds default, which causes our consumer to not see the changes to a specific topic after reading another one first. Setting the max age to 500ms will make it refresh faster, so the consumer will see the changes:

props.put("metadata.max.age.ms", "500");

**Comment by charithe** [comment]
Makes sense. I have added that override to the built-in consumer properties. I also made the `RecordConsumer` public so that it can be used with your own consumer if needed.

2.5-SNAPSHOT is on Sonatype snapshots now. I'll do a release in a couple of days.

**Pull request closed without merging**
