### PR TITLE
Add support for external Zookeeper (TestingServer)

### PR DESCRIPTION
**Pull request by jakrol**

### CODE REVIEW

**Comment by charithe** [comment]
Hi, thanks for the PR. I think it would be better to pass in a Zookeeper quorum string instead of a `TestingServer` as that would be more generic. It would allow others to use any ZK (even externally installed ones) and it also makes it very clear that the Kafka JUnit rule is not going to be responsible for the lifecycle of the ZK server used in the test.

**Comment by jakrol** [comment]
Hi, thanks for your comment.

Your suggestion would't work in our use case: we are using KafkaJunitRule together with an Apache StormRule and a ZookeeperRule. Since the zookeeper port is choosen randomly and during @Before execution in the ZookeeperRule, we are not able to provide a Zookeeper quorum string when creating the KafkaJunitRule.  

Basically out setup looks like
> static final ZookeeperJunitRule zookeeper = new ZookeeperJunitRule();
> static final KafkaJunitRule kafka = new KafkaJunitRule(zookeeper);
> static final StormClusterRule storm = new StormClusterRule(zookeeper);
	
> @ClassRule
> public static final RuleChain ruleChain = ruleChain.outerRule(zookeeper).around(kafka).around(storm);

I would suggest to use a Supplier to provide the zkQuorumString: https://gist.github.com/jakrol/2a65c41cefcd200b672c2b2483187e3f

If you agree I will close then pull request and create another one.

**Comment by charithe** [comment]
That is indeed a tricky situation. I'd just like to understand the problem a little bit better before accepting the PR because I'll have to maintain it for a long time once it's in master. Can you point me to the `ZookeeperJunitRule` and the `StormClusterRule` that you're referencing in the snippet please. Google is failing me.

**Comment by charithe** [comment]
Since I haven't heard anything back and the code has been significantly refactored, I am closing this PR.

**Pull request closed without merging**
