### PR TITLE
Upgraded kafka to 1.1.0

### PR DESCRIPTION
**Pull request by FrederikP**
Tests were green locally and only a slight rename was a breaking change, at least as far I can tell.

### CODE REVIEW

**Comment by tomashanley-toast** [comment]
You'll need to update the list of kafka-junit versions : kafka-versions in the Readme.

@charithe Presumably we'll also need to bump the minor version of this and release?

**Comment by hanleyt** [comment]
You'll also need to update the versions in the readme also.
@charithe presumably we'll also need to bump the minor version of this and release?

**Comment by FrederikP** [comment]
> You'll also need to update the versions in the readme also.
@hanleyt I was assuming that it would only confuse people reading the README on github as long as the new version in not released.

**Comment by hanleyt** [comment]
Ah ok cool, just something to keep in mind anyways. Thanks!

**Comment by charithe** [comment]
Thank you!

**Comment by adriancole** [comment]
can we get this cut for the 4.0.x line?

**Comment by charithe** [comment]
This PR is included in the 4.1.1 release.

**Comment by adriancole** [comment]
right I meant 4.0.1 (not junit 5) can that be done?

**Comment by hanleyt** [comment]
The latest release should be fully JUnit4 compatible. Is this not the case?

**Comment by adriancole** [comment]
I will try it. Just the release matrix on the README made me think I would
need to also use junit 5.

**Comment by FrederikP** [comment]
It works with JUnit4. Some IDEs try to run tests with JUnit5 though, because they find JUnit5 packages in the dependencies (e.g. Eclipse). Maybe it's possible to exclude those, when they are not used, but I haven't tried that yet. Manually telling eclipse to use JUnit4 works.

**Comment by charithe** [comment]
I'll update the README. It is becoming a bit unwieldy. We don't really need a release for every Kafka version as the API is quite stable. It's just easier for new users to start using the library if the Kafka client is bundled. 

I haven't tested this myself, but I am fairly confident that you could keep using any 4.x version of kafka-junit with any Kafka 1.x version by just adding an exclusion rule to filter out the bundled Kafka client.

**Comment by FrederikP** [comment]
Actually in this case (1.0.1 -> 1.1.0) this was not the case. I did exclude the bundled kafka client and tried to use kafka-junit 4.1.0 with kafka 1.1.0 and there were API incompatibilities.
If it would have worked, I would've not seen any need for submitting this pull request.

**Comment by charithe** [comment]
Thanks for clearing that out. Just to be clear, I very much appreciate your PR. I was just wondering whether it was possible to let advanced users update the Kafka version without having to figure out the version of kafka-junit that goes with it. It's quite clear that it is not the case in this instance.

**Pull request merged**
